{"uid":"a31431b85d327c86","name":"0202 should get name","fullName":"after hook failure 0202 should get name","historyId":"3665c5ee-0a1d-57ca-86c3-e4971776822d","time":{"start":1717342266871,"stop":1717342267354,"duration":483},"status":"failed","statusMessage":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","statusTrace":"Error: Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`\n    at Context.eval (webpack://cypress-ts-example/./cypress/e2e/before-after-hook/after-fail.cy.ts:12:0)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","statusTrace":"Error: Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`\n    at Context.eval (webpack://cypress-ts-example/./cypress/e2e/before-after-hook/after-fail.cy.ts:12:0)","steps":[{"name":"\"before each\" hook","time":{"start":1717342266874,"stop":1717342267165,"duration":291},"status":"passed","steps":[{"name":"intercept: mytest.com**","time":{"start":1717342266896,"stop":1717342266900,"duration":4},"status":"passed","steps":[{"name":"route","time":{"start":1717342266897,"stop":1717342266897,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"attachmentStep":false,"hasContent":false}],"attachments":[{"uid":"1141686d3969ef78","name":"intercept: mytest.com** args","source":"1141686d3969ef78.json","type":"application/json","size":1948}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":1,"attachmentStep":false,"hasContent":true},{"name":"visit: mytest.com","time":{"start":1717342266900,"stop":1717342267152,"duration":252},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"attachmentStep":false,"hasContent":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":3,"attachmentsCount":1,"attachmentStep":false,"hasContent":true},{"name":"get: [data-test-id=\"data-name-section\"] input","time":{"start":1717342267153,"stop":1717342267160,"duration":7},"status":"passed","steps":[{"name":"assert: expected **<input>** to exist in the DOM","time":{"start":1717342267157,"stop":1717342267157,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"attachmentStep":false,"hasContent":false},{"name":"assert: expected **<input>** to have attribute **placeholder** with the value **name**","time":{"start":1717342267159,"stop":1717342267159,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"attachmentStep":false,"hasContent":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":2,"attachmentsCount":0,"attachmentStep":false,"hasContent":true}],"attachments":[{"uid":"65c49f28873348e6","name":"after hook failure -- 0202 should get name -- after all hook teardown app (failed).png","source":"65c49f28873348e6.png","type":"image/png","size":70672}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":7,"attachmentsCount":2,"attachmentStep":false,"hasContent":true},"afterStages":[{"name":"\"after all\" hook: teardown app","time":{"start":1717342267207,"stop":1717342267329,"duration":122},"status":"failed","statusMessage":"Fail in after hook","statusTrace":"Error: Fail in after hook\n    at Context.eval (webpack://cypress-ts-example/./cypress/e2e/before-after-hook/after-fail.cy.ts:12:0)","steps":[{"name":"log: setup step after all tests in suite","time":{"start":1717342267164,"stop":1717342267166,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"attachmentStep":false,"hasContent":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":0,"attachmentStep":false,"hasContent":true},{"name":"video","time":{"start":1717342268480,"stop":1717342268480,"duration":0},"status":"passed","steps":[],"attachments":[{"uid":"a7ce280ad368fc3c","name":"after-fail.cy.ts.mp4","source":"a7ce280ad368fc3c.mp4","type":"video/mp4","size":118965}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":1,"attachmentStep":false,"hasContent":true}],"labels":[{"name":"package","value":"cypress.e2e.before-after-hook.after-fail.cy.ts"},{"name":"path","value":"cypress/e2e/before-after-hook/after-fail.cy.ts"},{"name":"host","value":"my-host"},{"name":"thread","value":"01"},{"name":"epic","value":"hooks"},{"name":"feature","value":"after"},{"name":"parentSuite","value":"cypress-ts"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"42255aea3b8d286","status":"failed","statusDetails":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","time":{"start":1717342199315,"stop":1717342199781,"duration":466}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":11,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":11},"items":[{"uid":"111ce6961a30bedb","status":"failed","statusDetails":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","time":{"start":1717015029437,"stop":1717015029927,"duration":490}},{"uid":"faf33fff0a9e5c8c","status":"failed","statusDetails":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","time":{"start":1699650602267,"stop":1699650603056,"duration":789}},{"uid":"59cfcd615511fa53","status":"failed","statusDetails":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","time":{"start":1699649935551,"stop":1699649936547,"duration":996}},{"uid":"fb4c89a7187a3be0","status":"failed","statusDetails":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","time":{"start":1699648363049,"stop":1699648365162,"duration":2113}},{"uid":"80de4892713cc4e8","status":"failed","statusDetails":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","time":{"start":1698676268649,"stop":1698676269213,"duration":564}},{"uid":"f1133bffdef6cba6","status":"failed","statusDetails":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","time":{"start":1696339486442,"stop":1696339487923,"duration":1481}},{"uid":"24043461f063ac73","status":"failed","statusDetails":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","time":{"start":1696338794597,"stop":1696338795144,"duration":547}},{"uid":"c628a23e054c3a4b","status":"failed","statusDetails":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","time":{"start":1696338366678,"stop":1696338367188,"duration":510}},{"uid":"11a6a030a8311fa7","status":"failed","statusDetails":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","time":{"start":1696337036104,"stop":1696337036668,"duration":564}},{"uid":"69dbf4a653a256a","status":"failed","statusDetails":"Fail in after hook\n\nBecause this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `after hook failure`","time":{"start":1696336902265,"stop":1696336903289,"duration":1024}}]},"tags":[]},"source":"a31431b85d327c86.json","parameterValues":[]}